# Generated by Django 4.0.6 on 2022-07-14 16:26

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_objeto', models.CharField(max_length=30)),
                ('etiqueta', models.IntegerField(default=0)),
                ('usuario', models.CharField(max_length=50)),
                ('setor', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt_cadastro', models.DateField()),
                ('observacao', models.TextField(max_length=300)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
